---
title: "Text Analysis"
author: "Sofia Fasullo"
date: "2022-12-05"
output: html_document
---

```{r setup, include=FALSE}
# Load some libraries
rm(list = ls())
library(tidycensus)
library(dplyr)
library(viridis)
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(stargazer)
library(readr)
library(tidyverse)
library(cluster)
library(factoextra)
library(kableExtra)
library(stringr)
library(tidytext)
library(yardstick)
library(rsample)
library(glmnet)
library(broom)
library(tmap)
options(scipen=999) #scientific notation off

# Functions and data directory
census_api_key("8c8e36c4b5046c4d7f8a5d9f0f7a7d0ddde86e8b")

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")
```


```{r import listings}

listings <- read_csv("https://github.com/SofiaFasullo/MUSA508-final-project/raw/main/listings.csv")

listing_details <- read_csv("https://github.com/SofiaFasullo/MUSA508-final-project/raw/main/listings_details.csv")
```

```{r clean data}

listing_details <- listing_details %>%
  select(1,23,26,29,39,40,49,50,52:57,60,61,80,96)

listings <- listings %>%
  select(1)

full_listings <- merge(listings,listing_details,by="id")

full_listings <- full_listings %>% mutate(price = price %>% str_remove_all("[$,]") %>% as.numeric())

full_listings.sf <- st_as_sf(full_listings,coords=c("longitude","latitude"),crs=4326)
```



